
# SEO settings
title: "sangho"
title2: "space" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://choisho.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# google_analytics: UA-XXXXX-XX
repo: http://github.com/choisho/choisho.github.io
disqus_shortname: "choishogithub"
# twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Sangho Choi"
  job      : "Front-end Engineer"
  bio      : "안녕하세요, 최상호에요."
  thumb    : /images/author.jpg
  email    : choisho1136@gmail.com
  url      : http://choisho.github.io
  github   : http://github.com/choisho
  twitter  : http://twitter.com/choisho
  

# social settings
og_locale: "KR"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
